= Grammar
:example-caption:

Do you know your nouns from your pronouns? What about your verbs from your adverbs? This page will give a basic introduction to different types of word that is most revelevant to these notes.

== Parts of Speech
This table covers the parts of speech you need to know about.

[cols="1,1,1"]
|===
|*Part of speech*
|*Definition*
|*Example*

|Noun
|A person, place, concept or thing.
|*Jim* plays *tennis* with his *racket*.

|Pronoun
|A noun that replaces another noun or noun phrase.
|Jim plays tennis. *He* often wins.

|Adjective
|A word or phrase that modifies a noun.
|Jim has a *red* racket.

|Noun phrase
|A group of words that acts as a noun.
|Jim has a *big red* racket.

|Verb
|An action word or phrase.
|Jim *plays* tennis.

|Adverb
|A word or phrase that modifies a verb, adjective or another adverb.
|Jim *expertly* plays tennis.

|Preposition
|A word or phrase specifying the positional relationship of two nouns.
|Jim's racket is often *in* his hand.

|Conjunction
|A word that connects two nouns or phrases.
|Jim's racket *and* tennis shoes are his most expensive pieces of equipment.

|Transition
|A word or phrase that connects two sentences.
|Jim plays tennis weekly. Consequently he is quite good.
|===

== Nouns

Nouns are words that represent people, places or things. Nouns can be concrete things such as *Jim*, *England* and *Racket*. However, they can also be more abstract concepts like *robustness* and *perfection*. Consider the following example passage from Google, with all the nouns highlighted in bold.

.{}
[example]
In the *framework*, an *object* must copy any underlying *values* that the *object* wants to change. The *protocol buffers* in the *codebase* are huge, so copying the *protocol buffers* is unacceptably expensive.


Consider the following passage. We will highlight the nouns it contains.

[example]
C enables programmers to control pointers and memory. Great power brings great responsibility.


.Solution
====
*C* enables *programmers* to control *pointers* and *memory*. Great *power* brings great *responsibility*.
====

Suppose that the second sentence was replaced with the following:

====
Great control brings great responsibility.
====

In this sentenece, *control* is a noun, despite the fact that *to control* was a verb in the first sentence. Many words have a dual purpose like this. They can be nouns in some contexts, and verbs in others.

== Pronouns

Pronouns act as pointers. They point to previously introduced nouns. Consider the example from the earlier table:

[sidebar]
Jim plays tennis. *He* often wins.

The pronoun *he* points to the noun *Jim* that is introduced in the first sentence.

Pronouns can replace longer passages. Consider this example:

====
Without warning, halfway through the user manual the language changed from English to French. *This* is poor documentation.
====

Consider the following passage. We will highlight the pronouns it contains.

====
The cafeteria featured peanut butter and plum jam on rye toast. Employees found it awesome and wished they could eat this every day.
====

.Solution
====
The cafeteria featured peanut butter and plum jam on rye toast. Employees found *it* awesome and wished *they* could eat *this* every day.
====

== Verbs

To quote most primary school teachers in the UK; _verbs are doing words_. Verbs are action words or phrases. They are used to represent the relationship between two nouns. Each sentence must contain at least one verb. Here are some examples of sentences containing one verb:

* Bill *likes* pizza.
* Tinky Winky *is* purple.
* Clangers *like* soup.

Sentences can contain multiple verbs. Here are some examples:

* Tinky Winky *is* purple and *likes* tubby custard.
* Bill *likes* pizza but *prefers* pasta.

There are instances when verbs consist of more than one word:

* Tinky Winky *was eating* their tubby custard an hour ago.
* Bill *will be eating* Pizza for his tea.

Consider the following passage. We will highlight the verbs it contains.

====
Samantha is coding Operation Bullwinkle in C{plus}{plus}. This project currently consumes over 80,000 lines of code. She previously used Python, but recently gravitated to C{plus}{plus}. Samantha leads a team of four software engineers, which will grow to six software engineers next quarter.
====

.Solution
====
Samantha *is coding* Operation Bullwinkle in C{plus}{plus}. This project currently *consumes* over 80,000 lines of code. She previously *used* Python, but recently *gravitated* to C{plus}{plus}. Samantha *leads* a team of four software engineers, which *will grow* to six software engineers next quarter.
====

== Adjectives & Adverbs

== Prepositions

== Conjunctions & Transitions



